CREATE TABLE respuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensajeRespuesta TEXT NOT NULL,
    id_topico BIGINT NOT NULL,
    fechaCreacionRespuesta TIMESTAMP NOT NULL,
    id_usuario BIGINT NOT NULL,
    fechaUltimaEdicion TIMESTAMP NOT NULL,
    solucion Boolean NOT NULL,
    CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id),
    CONSTRAINT fk_respuestas_topico FOREIGN KEY (id_topico) REFERENCES topicos(id)
);